Commit actividad 5 tests

diff --git a/.github/workflows/main_workflow.yml b/.github/workflows/main_workflow.yml
--- a/.github/workflows/main_workflow.yml
+++ b/.github/workflows/main_workflow.yml
@@ -5,50 +5,59 @@ on:
   push:
     branches:
       # - nodejs_linter_job
-      - nodejs_envirenment_job # solo se ejecutara en un push a esta rama
+      - nodejs_test_error_job # solo se ejecutara en un push a esta rama
 # ahora ejecutamos este job llamado linter execution
 jobs:
-  # linter_execution:
-  #   runs-on: ubuntu-latest
+  linter_execution:
+    runs-on: ubuntu-latest
 
-  #   strategy:
-  #     matrix:
-  #       node-version: [16, 18, 20] # Versions de Node.js que queremos probar
+    strategy:
+      matrix:
+        node-version: [16] # Versions de Node.js que queremos probar
+        #node-version: [16, 18, 20] # Versions de Node.js que queremos probar
+    steps:
+      # Step 1: Checkout code
+      - name: Checkout code #nombre del step
+        uses: actions/checkout@v2 # la accion que ejecuta
 
-  #   steps:
-  #     # Step 1: Checkout code
-  #     - name: Checkout code #nombre del step
-  #       uses: actions/checkout@v2 # la accion que ejecuta
+      - name: Setting node version
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }} # Utilitzamos cada version del `matrix`
 
-  #     - name: Setting node version
-  #       uses: actions/setup-node@v3
-  #       with:
-  #         node-version: ${{ matrix.node-version }} # Utilitzamos cada version del `matrix`
-
-  #     # Step 2: Linter execution
-  #     - name: Linter execution #nombre del step
-  #       uses: github/super-linter@v4 # la accion que ejecuta
-  #       env:
-  #         DEFAULT_BRANCH: nodejs_example
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #         LINTER_RULES_PATH: /
-  #         JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
-  #         VALIDATE_JAVASCRIPT_ES: true
+      # Step 2: Linter execution
+      - name: Linter execution #nombre del step
+        uses: github/super-linter@v4 # la accion que ejecuta
+        env:
+          DEFAULT_BRANCH: nodejs_example
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          LINTER_RULES_PATH: /
+          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
+          VALIDATE_JAVASCRIPT_ES: true
 
   test-execution:
-    #needs: linter_execution # Dependencia del job linter_execution se necesita que acabe el job anterior
+    needs: linter_execution # Dependencia del job linter_execution se necesita que acabe el job anterior
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2 # Descarga el codigo para ejecutar pruebas
+        uses: actions/checkout@v3 # Descarga el codigo para ejecutar pruebas
+
       - name: Run_jest_test
-        run: | # instala jest que es un framework de pruebas de javascript.
-          npm install jest  
-          npm test
+        id: jest # Assigna un ID per referenciarlo en el step posteriormente
+        continue-on-error: true
+
+        run: | # instala jest que es un framework de pruebas de javascript./ npm test ejecuta el script test del fichero package.json
+          npm install jest --legacy-peer-deps
+          npm test 
+          
+      - name: Fails
+        if: steps.jest.outcome != 'success'
+        run: echo "Se ha producido un error en el test " && exit 1
+
 
   environtment_test_execution:
-    needs: [test-execution]
     runs-on: ubuntu-latest
+    needs: [test-execution]
     env:
       DESTINATION_PERSON: "2DAW"
     steps:
